---
#
# set up the contractor laptop
#
- hosts: contractor
  remote_user: ubuntu
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: sudo apt-get install -y python-simplejson
    - name: update /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: '127.0.0.1 contractor'
    - name: update /etc/hostname
      raw: echo "contractor" > /etc/hostname
    - name: persist new hostname
      raw: hostname contractor
  roles:
    - { role: mutt_contractor }
    - { role: fetchmail }
    - { role: mpack }
    - { role: wazuh_agent_contractor }
    - { role: packetbeat }