---
#
# Installing Elasticsearch
#
# Adds the apt-key for Elasticsearch
- name: Add Elasticsearch apt-key
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present
# Add the Elasticsearch APT-repository
- name: Adding Elasticsearch APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/p... stable main
    state: present
# Install Elasticsearch
- name: Update repositories cache and install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes
# Update Elasticsearch config file to only allow localhost connections
- name: Updating the config file to restrict outside access
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'
# Restart Elasticsearch
- name: Restarting Elasticsearch
  service:
    name: elasticsearch
    state: restarted
